### ISSUE TITLE
Can't update zoner AV

### ISSUE THREAD

**Issue by unstppbl** [malice-plugins/zoner#1]
Error running update command:
```bash
╰$ docker run --name=zoner malice/zoner update
Updating Zoner...
time="2018-08-06T09:27:12Z" level=fatal msg="exit status 1" category=av path= plugin=zoner
```

**Comment by blacktop** [comment]
So something is wrong with the Zoner update servers.  When building this image you get: `ERROR: Update failed - server encountered an error: "Cannot query SQL database"`  So there is a problem with zoner itself, which is why i disabled this plugin in MaliceIO https://github.com/maliceio/malice/blob/master/plugins/plugins.toml#L223
